### ISSUE TITLE
Focal image: things left to fix

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ubiquity_main#259]
- [x] desktop environment https://github.com/UbiquityRobotics/pi_image2/issues/24
- [x] RTC delay at boot without a MCB
- [x] buildbot upload
- [x] Insert py2 hack https://github.com/UbiquityRobotics/ota_update/pull/13
- [x] solve static IP setting https://github.com/UbiquityRobotics/magni_robot/issues/185
- [x] working raspicam
- [x] shorten boot times https://github.com/UbiquityRobotics/pi_image2/issues/33
- [x] add terminal and a bunch of installs https://github.com/UbiquityRobotics/robot_testing/issues/18#issuecomment-1031244237
- [ ] final tweaks

**Comment by MoffKalast** [comment]
Question, @JanezCim does pifi now work normally on focal? Can we set up a static ip for the lidar and all that? I think there were some issues with the network manager removal.

**Comment by JanezCim** [comment]
Thanks for pointing that out! I did not check if I can setup the static IP, can you please try it and see if it works. You can comment more on the issue about that on https://github.com/UbiquityRobotics/magni_robot/issues/185

**Comment by JanezCim** [comment]
With @rohbotics we agreed that the focal image creation is now at a level where we can release a kind of "release-candidate". This way we have some real world user feedback on issues that are going to be popping up. Not sure how to actually do that exactly, should i create dev and base images that have "release-candidate" in the name and maybe have the image print on every ssh a message, kindof: "This is not fully released image, some problems can still occour - please report problems onto : TODO which repo should they report problems to?"

**Comment by JanezCim** [comment]
I will mark this as done, since we are releasing beta2 image soon
